

mailer:
    user_name: 'muhammad.adeel@devsinc.com'
    password: 'wonngfwtyoj'
    address: 'smtp.gmail.com'

host:
    host: localhost
    port: 3000
secret:
    secret_key:  '95e81383b0f0a504e734792be2ed6002167c20bb210e13
                  c781e15cc34bf36093e5d214d9c5bae7d607fafbb79a1a9
                  b2ee653daf21e32d61d6efd1bc85146d128'
